name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jetify-com/devbox-install-action@v0.15.0
        with:
          enable-cache: 'true'

      - name: Build site
        run: devbox run -- make deploy
        env:
          GOPATH: /home/runner/go

      - name: Verify output
        run: test -f web/index.html
